site_name: CtrlAltQuest Documentation
nav:
  - Home: index.md
  - Pathfinder 2e:
      - Bonesaw Character Sheet: docs/Pathfinder2e/Bonesaw-CharacterSheet.pdf
      - Remaster Player Core Character Sheet: docs/Pathfinder2e/RemasterPlayerCoreCharacterSheet.pdf
theme:
  name: mkdocs
  user_color_mode_toggle: true
  color_mode: dark
